export type MockJob = {
  id: string;
  title: string;
  company: string;
  salary: string;
  location: string;
  hours: string;
  categories: string[];
  car: boolean;
  license: boolean;
  housing: boolean;
  weekend: boolean;
  description: string;
  requirements: string[];
  questions: string[];
  states?: string[];
};

export const MOCK_JOBS: MockJob[] = [];

const _UNUSED: MockJob[] = [
  {
    id: "m1",
    title: "לוקסמיט - ניו יורק",
    company: "Empire Lock Solutions",
    salary: "$1,100-$1,600/שבוע",
    location: "Queens, NY",
    hours: "08:00-17:00",
    categories: ["locksmith"],
    car: true,
    license: true,
    housing: false,
    weekend: false,
    description: "חברת מנעולים ותיקה בקווינס מחפשת טכנאי מנוסה. עבודה על בתים, עסקים ורכבים. לקוחות קבועים, רכב חברה וציוד מסופק. צוות ישראלי נעים.",
    requirements: ["ניסיון בלוקסמית", "רישיון נהיגה", "אמינות ומקצועיות"],
    questions: ["כמה שנות ניסיון יש לך?", "האם יש לך רישיון נהיגה אמריקאי?"],
  },
  {
    id: "m2",
    title: "לוקסמיט - ניו ג׳רסי",
    company: "Garden State Locks",
    salary: "$1,000-$1,500/שבוע",
    location: "Newark, NJ",
    hours: "07:30-17:00",
    categories: ["locksmith"],
    car: true,
    license: true,
    housing: true,
    weekend: false,
    description: "חברה ישראלית בניו ג׳רסי מחפשת טכנאי מנעולים. דיור מסובסד זמין. שכר גבוה + בונוסים. אחרי 3 חודשים אפשרות להתקדם לתפקיד בכיר.",
    requirements: ["ניסיון מועדף", "רישיון נהיגה", "נכונות ללמוד"],
    questions: ["האם יש לך ניסיון בלוקסמית?", "האם אתה זמין להתחיל מיד?"],
  },
  {
    id: "m3",
    title: "מכונאי רכב - ברוקלין",
    company: "Brooklyn Auto Garage",
    salary: "$1,200-$1,800/שבוע",
    location: "Brooklyn, NY",
    hours: "08:00-17:30",
    categories: ["garage"],
    car: false,
    license: true,
    housing: false,
    weekend: false,
    description: "גראז' ישראלי מוביל בברוקלין מחפש מכונאי מנוסה. עבודה על כל סוגי הרכבים. אווירה משפחתית, שכר גבוה, כלי עבודה מסופקים.",
    requirements: ["ניסיון של 2+ שנים", "ידע בדיאגנוסטיקה", "כלי עבודה משלך - יתרון"],
    questions: ["כמה שנות ניסיון יש לך במכונאות?", "האם יש לך כלי עבודה משלך?"],
  },
  {
    id: "m4",
    title: "עוזר מכונאי - מיאמי",
    company: "South Florida Auto",
    salary: "$800-$1,200/שבוע",
    location: "Miami, FL",
    hours: "07:00-16:00",
    categories: ["garage"],
    car: false,
    license: false,
    housing: true,
    weekend: false,
    description: "גראז' פעיל במיאמי מחפש עוזר מכונאי. הכשרה מלאה תינתן. דיור מסובסד זמין. צוות ישראלי-אמריקאי. מתאים לאנשים שרוצים ללמוד מקצוע.",
    requirements: ["נכונות ללמוד", "כושר פיזי", "אנגלית בסיסית"],
    questions: ["האם עבדת בגראז' בעבר?", "מתי תוכל להתחיל?"],
  },
  {
    id: "m5",
    title: "ניקוי צינורות - ניו יורק",
    company: "Fresh Air NYC",
    salary: "$950-$1,400/שבוע",
    location: "Bronx, NY",
    hours: "08:00-17:00",
    categories: ["airduct"],
    car: true,
    license: false,
    housing: false,
    weekend: true,
    description: "חברת אייר-דק מובילה בניו יורק מחפשת טכנאים. עבודה בבתים ועסקים ברחבי ניו יורק. ציוד מסופק, רכב חברה, שכר שעתי גבוה + עמלות.",
    requirements: ["כושר פיזי", "לא חושש מחללים צרים", "אמינות"],
    questions: ["האם יש לך ניסיון בניקוי צינורות?", "האם אתה חושש מחללים צרים?"],
  },
  {
    id: "m6",
    title: "אייר-דק - לוס אנג׳לס",
    company: "LA Air Masters",
    salary: "$1,000-$1,500/שבוע",
    location: "Los Angeles, CA",
    hours: "07:00-16:00",
    categories: ["airduct"],
    car: true,
    license: false,
    housing: true,
    weekend: false,
    description: "חברה ישראלית בלוס אנג׳לס מחפשת טכנאי אייר-דק. דיור זמין, קהילה ישראלית גדולה באזור. הכשרה מלאה. תנאים מצוינים.",
    requirements: ["כושר פיזי טוב", "נכונות לעבוד"],
    questions: ["האם אתה גר בלוס אנג׳לס?", "האם אתה זמין להתחיל מיד?"],
  },
  {
    id: "m7",
    title: "מנקה ארובות - סטטן איילנד",
    company: "NY Chimney Pros",
    salary: "$1,000-$1,400/שבוע",
    location: "Staten Island, NY",
    hours: "08:00-17:00",
    categories: ["chimney"],
    car: true,
    license: false,
    housing: false,
    weekend: false,
    description: "חברת צ׳ימני ותיקה בסטטן איילנד מחפשת עובד. עבודה בניו יורק וניו ג׳רסי. ציוד מלא, רכב חברה. לא חוששים מגבהים - זה המקצוע בשבילך.",
    requirements: ["לא חושש מגבהים", "כושר פיזי טוב", "אמינות"],
    questions: ["האם אתה חושש מגבהים?", "האם יש לך ניסיון בצ׳ימני?"],
  },
  {
    id: "m8",
    title: "צ׳ימני - ניו ג׳רסי",
    company: "NJ Chimney Care",
    salary: "$950-$1,350/שבוע",
    location: "Hoboken, NJ",
    hours: "07:30-16:30",
    categories: ["chimney"],
    car: true,
    license: true,
    housing: false,
    weekend: false,
    description: "חברת צ׳ימני בניו ג׳רסי מחפשת טכנאי. עבודה עם לקוחות קבועים ומוניטין מעולה. רכב חברה + ביטוח. שעות נוחות, ימי חול בלבד.",
    requirements: ["לא חושש מגבהים", "רישיון נהיגה", "ניסיון - יתרון"],
    questions: ["האם יש לך רישיון נהיגה?", "האם אתה גר בניו ג׳רסי?"],
  },
  {
    id: "m9",
    title: "פועל בנייה - ניו יורק",
    company: "Israeli Builders NYC",
    salary: "$1,100-$1,700/שבוע",
    location: "Queens, NY",
    hours: "07:00-16:00",
    categories: ["construction"],
    car: false,
    license: false,
    housing: false,
    weekend: false,
    description: "חברת בנייה ישראלית גדולה בניו יורק מחפשת פועלים. עבודה בפרויקטים גדולים ברחבי העיר. שכר גבוה, ביטוח, ציוד מסופק. אפשרות לקבלנות עצמאית.",
    requirements: ["ניסיון בבנייה", "כושר פיזי", "לא חושש מגבהים"],
    questions: ["כמה שנות ניסיון יש לך בבנייה?", "האם יש לך OSHA certification?"],
  },
  {
    id: "m10",
    title: "קונסטרשן - פלורידה",
    company: "Sunshine Construction",
    salary: "$1,000-$1,500/שבוע",
    location: "Orlando, FL",
    hours: "06:30-15:30",
    categories: ["construction"],
    car: false,
    license: false,
    housing: true,
    weekend: false,
    description: "חברת בנייה בפלורידה עם פרויקטים רבים. מחפשים פועלים מנוסים. דיור מסובסד זמין. צוות ישראלי נהדר. עבודה בחוץ בסביבה נעימה.",
    requirements: ["ניסיון בבנייה", "כושר פיזי", "נכונות לעבוד בחום"],
    questions: ["האם עבדת בבנייה בארה\"ב?", "האם תוכל לעבוד בחום?"],
  },
  {
    id: "m11",
    title: "מנקה שטיחים - ניו יורק",
    company: "Crown Carpet NY",
    salary: "$900-$1,300/שבוע",
    location: "Long Island, NY",
    hours: "08:00-17:00",
    categories: ["carpets"],
    car: true,
    license: false,
    housing: false,
    weekend: true,
    description: "חברת ניקוי שטיחים ותיקה בניו יורק. לקוחות קבועים עם טיפים מעולים. ציוד מקצועי, רכב חברה. הכשרה מלאה לחסרי ניסיון.",
    requirements: ["כושר פיזי", "אמינות", "נכונות ללמוד"],
    questions: ["האם יש לך ניסיון בניקוי שטיחים?", "האם יש לך רישיון נהיגה?"],
  },
  {
    id: "m12",
    title: "ניקוי שטיחים - מיאמי",
    company: "Miami Carpet Kings",
    salary: "$850-$1,250/שבוע",
    location: "Aventura, FL",
    hours: "08:00-17:00",
    categories: ["carpets"],
    car: true,
    license: false,
    housing: false,
    weekend: false,
    description: "חברת ניקוי שטיחים במיאמי עם קהל לקוחות ישראלי גדול. עבודה בבתים ועסקים. ציוד חדיש. מחפשים 2 עובדים חרוצים ואמינים.",
    requirements: ["כושר פיזי", "יחסי אנוש טובים", "עברית ואנגלית"],
    questions: ["באיזה אזור במיאמי אתה גר?", "האם יש לך ניסיון בניקוי?"],
  },
  {
    id: "m13",
    title: "מכירות עגלות - ניו יורק",
    company: "Premier Kiosk Group",
    salary: "$800-$2,000/שבוע",
    location: "Manhattan, NY",
    hours: "10:00-21:00",
    categories: ["sales"],
    car: false,
    license: false,
    housing: false,
    weekend: true,
    description: "חברת מכירות ישראלית מובילה בקניוני ניו יורק. שכר בסיסי + עמלות גבוהות. מתאים לאנשים חברותיים עם כריזמה. הכשרה מלאה.",
    requirements: ["כריזמה ויכולת מכירה", "עברית ואנגלית", "נכונות לעמוד שעות"],
    questions: ["האם יש לך ניסיון במכירות?", "האם אתה מרגיש נוח לפנות לאנשים?"],
  },
  {
    id: "m14",
    title: "מכירות - לאס וגאס",
    company: "Vegas Sales IL",
    salary: "$1,000-$2,500/שבוע",
    location: "Las Vegas, NV",
    hours: "10:00-22:00",
    categories: ["sales"],
    car: false,
    license: false,
    housing: true,
    weekend: true,
    description: "חברת מכירות בלאס וגאס עם תיירים מכל העולם. שכר גבוה מאוד בעמלות. דיור זמין. מתאים לדוברי שפות רבות. עונה גבוהה כל השנה.",
    requirements: ["יכולת מכירה", "שפות - יתרון", "אנרגיה גבוהה"],
    questions: ["באילו שפות אתה דובר?", "האם יש לך ניסיון במכירות?"],
  },
  {
    id: "m15",
    title: "עבודה כללית - שיקגו",
    company: "Chicago Israeli Services",
    salary: "$850-$1,200/שבוע",
    location: "Chicago, IL",
    hours: "08:00-17:00",
    categories: ["other"],
    car: false,
    license: false,
    housing: false,
    weekend: false,
    description: "חברת שירותים ישראלית בשיקגו מחפשת עובד רב-תכליתי. עבודות תחזוקה ועזרה כללית. צוות ישראלי קטן ונעים. מתאים לכל מי שרוצה להתחיל.",
    requirements: ["נכונות לעבוד", "אמינות", "כושר פיזי בסיסי"],
    questions: ["מה ניסיון העבודה שלך?", "מתי תוכל להתחיל?"],
  },
];
