export type MockJob = {
  id: string;
  title: string;
  company: string;
  salary: string;
  location: string;
  hours: string;
  categories: string[];
  car: boolean;
  license: boolean;
  housing: boolean;
  weekend: boolean;
  description: string;
  requirements: string[];
  questions: string[];
};

export const MOCK_JOBS: MockJob[] = [
  {
    id: "m1",
    title: "לוקסמיט - מומחה מנעולים",
    company: "NYC Lock Pro",
    salary: "$800-1,200/שבוע",
    location: "Brooklyn, NY",
    hours: "8:00-17:00",
    categories: ["locksmith"],
    car: false,
    license: true,
    housing: false,
    weekend: false,
    description: "אנחנו מחפשים לוקסמיט מנוסה להצטרף לצוות שלנו בברוקלין. העבודה כוללת פתיחת מנעולים, החלפת מנעולים ביתיים ומסחריים, והתקנת מערכות אבטחה. סביבת עבודה נעימה עם צוות ישראלי.",
    requirements: ["ניסיון של לפחות שנה בתחום", "רישיון עבודה תקף", "אמינות ומקצועיות", "יכולת עבודה עצמאית"],
    questions: ["כמה שנות ניסיון יש לך כלוקסמיט?", "האם יש לך רישיון עבודה?", "מה הזמינות שלך?"],
  },
  {
    id: "m2",
    title: "טכנאי לוקסמיט מנוסה",
    company: "Fast Lock NY",
    salary: "$900-1,400/שבוע",
    location: "Manhattan, NY",
    hours: "9:00-18:00",
    categories: ["locksmith"],
    car: true,
    license: true,
    housing: false,
    weekend: true,
    description: "Fast Lock NY מגייסת טכנאי לוקסמיט מנוסה למנהטן. כולל רכב חברה, ציוד מקצועי, ומשכורת מצוינת. עבודה בין לקוחות עסקיים ופרטיים ברחבי NYC.",
    requirements: ["ניסיון של 2+ שנים", "רישיון נהיגה", "רישיון עבודה", "זמינות לסופי שבוע"],
    questions: ["האם יש לך ניסיון עם מנעולים מסחריים?", "האם אתה זמין לסופי שבוע?", "האם יש לך רישיון נהיגה אמריקאי?"],
  },
  {
    id: "m3",
    title: "מכונאי רכב - גראז",
    company: "Queens Auto",
    salary: "$1,000-1,500/שבוע",
    location: "Queens, NY",
    hours: "8:00-17:00",
    categories: ["garage"],
    car: false,
    license: true,
    housing: false,
    weekend: false,
    description: "גראז מוביל בקווינס מחפש מכונאי מנוסה. עבודה על מגוון רכבים, סביבה מקצועית, ציוד חדיש. הצוות כולל ישראלים ותיקים עם ניסיון רב בשוק האמריקאי.",
    requirements: ["ניסיון של 2+ שנים במכונאות", "יכולת אבחון מחשבים", "רישיון עבודה תקף", "אנגלית בסיסית"],
    questions: ["כמה שנות ניסיון יש לך?", "אילו סוגי רכבים עבדת עליהם?", "האם יש לך ניסיון עם מכונות אבחון?"],
  },
  {
    id: "m4",
    title: "טכנאי גראז בכיר",
    company: "Bronx Motors",
    salary: "$1,200-1,800/שבוע",
    location: "Bronx, NY",
    hours: "7:00-16:00",
    categories: ["garage"],
    car: true,
    license: true,
    housing: true,
    weekend: false,
    description: "Bronx Motors מחפשת טכנאי בכיר עם ניסיון רב. חבילת שכר מצוינת הכוללת רכב ואפשרות דיור. הזדמנות מצוינת להתקדם בקריירה בשוק הניו יורקי.",
    requirements: ["ניסיון של 5+ שנים", "רישיון נהיגה", "רישיון עבודה", "ניסיון בניהול"],
    questions: ["כמה שנות ניסיון יש לך?", "האם יש לך ניסיון בניהול צוות?", "האם אתה מעוניין בדיור?"],
  },
  {
    id: "m5",
    title: "מומחה אייר-דק ניקוי תעלות",
    company: "Air Clean NYC",
    salary: "$700-1,100/שבוע",
    location: "Staten Island, NY",
    hours: "8:00-17:00",
    categories: ["airduct"],
    car: true,
    license: false,
    housing: false,
    weekend: false,
    description: "Air Clean NYC מגייסת מומחה ניקוי תעלות אוויר בסטייטן איילנד. עבודה בבתים ועסקים, כולל רכב חברה וציוד. אין צורך בניסיון קודם — נלמד אותך הכל.",
    requirements: ["זמינות מלאה", "רישיון נהיגה", "כושר פיזי", "נכונות ללמוד"],
    questions: ["האם יש לך רישיון נהיגה?", "האם אתה זמין להתחיל מיד?", "האם יש לך ניסיון בתחום?"],
  },
  {
    id: "m6",
    title: "טכנאי מיזוג אוויר ואייר-דק",
    company: "Cool Air Solutions",
    salary: "$850-1,300/שבוע",
    location: "New Jersey",
    hours: "9:00-18:00",
    categories: ["airduct"],
    car: true,
    license: false,
    housing: false,
    weekend: true,
    description: "Cool Air Solutions מגייסת טכנאי מיזוג ואייר-דק לניו ג'רזי. עבודה בצוות קטן ומשפחתי, כולל רכב. אפשרות להתפתחות מקצועית מהירה.",
    requirements: ["ניסיון בסיסי במיזוג אוויר", "רישיון נהיגה", "זמינות לסופי שבוע", "כושר פיזי"],
    questions: ["האם יש לך ניסיון עם מזגנים?", "האם אתה מוכן לעבוד בניו ג'רזי?", "האם אתה זמין לסופי שבוע?"],
  },
  {
    id: "m7",
    title: "מנקה צ'ימני מקצועי",
    company: "Chimney Masters",
    salary: "$750-1,100/שבוע",
    location: "Brooklyn, NY",
    hours: "8:00-16:00",
    categories: ["chimney"],
    car: true,
    license: false,
    housing: false,
    weekend: false,
    description: "Chimney Masters מחפשת מנקה צ'ימני לברוקלין. עבודה עם ציוד מקצועי, כולל רכב חברה. לא נדרש ניסיון — הכשרה מלאה ניתנת. צוות ישראלי נחמד.",
    requirements: ["כושר פיזי טוב", "לא חשש מגבהים", "רישיון נהיגה", "אמינות"],
    questions: ["האם יש לך פחד מגבהים?", "האם אתה בכושר פיזי?", "האם יש לך ניסיון בתחום?"],
  },
  {
    id: "m8",
    title: "טכנאי צ'ימני ותנורים",
    company: "NY Chimney Pro",
    salary: "$800-1,200/שבוע",
    location: "Long Island, NY",
    hours: "7:00-15:00",
    categories: ["chimney"],
    car: true,
    license: true,
    housing: false,
    weekend: false,
    description: "NY Chimney Pro מגייסת טכנאי מנוסה לאי הארוך. עבודה על צ'ימניים, תנורי עץ ומערכות חימום. כולל רכב ועמלות על עבודות נוספות.",
    requirements: ["ניסיון של שנה+", "רישיון נהיגה", "רישיון עבודה", "ידע בחימום"],
    questions: ["האם יש לך ניסיון עם תנורי עץ?", "האם אתה מוכן לעבוד בלונג איילנד?", "האם יש לך ניסיון בתחום?"],
  },
  {
    id: "m9",
    title: "פועל בנייה - קונסטרשן",
    company: "Build NY Corp",
    salary: "$900-1,300/שבוע",
    location: "Manhattan, NY",
    hours: "7:00-16:00",
    categories: ["construction"],
    car: false,
    license: false,
    housing: false,
    weekend: false,
    description: "Build NY Corp מחפשת פועל בנייה למנהטן. עבודה על פרויקטים גדולים בלב ניו יורק. שכר גבוה, תנאים טובים, וצוות ישראלי מנוסה.",
    requirements: ["כושר פיזי", "ניסיון בסיסי בבנייה", "זמינות מלאה", "אמינות"],
    questions: ["האם יש לך ניסיון בבנייה?", "האם אתה זמין להתחיל מיד?", "מה ניסיון הבנייה שלך?"],
  },
  {
    id: "m10",
    title: "מנהל אתר בנייה",
    company: "Metro Construction",
    salary: "$1,400-2,000/שבוע",
    location: "Queens, NY",
    hours: "6:00-15:00",
    categories: ["construction"],
    car: true,
    license: true,
    housing: false,
    weekend: false,
    description: "Metro Construction מגייסת מנהל אתר בנייה מנוסה לקווינס. אחריות על פרויקטים גדולים, ניהול צוות, ותיאום עם לקוחות. חבילת שכר מצוינת.",
    requirements: ["ניסיון ניהולי של 3+ שנים", "רישיון נהיגה", "רישיון עבודה", "אנגלית ברמה טובה"],
    questions: ["כמה שנות ניסיון ניהולי יש לך?", "האם אתה מכיר את תקנות הבנייה האמריקאיות?", "מה הפרויקט הגדול ביותר שניהלת?"],
  },
  {
    id: "m11",
    title: "מנקה שטיחים ורצפות",
    company: "Clean Carpets NYC",
    salary: "$650-950/שבוע",
    location: "Brooklyn, NY",
    hours: "8:00-17:00",
    categories: ["carpets"],
    car: true,
    license: false,
    housing: false,
    weekend: false,
    description: "Clean Carpets NYC מחפשת מנקה שטיחים לברוקלין. עבודה עם ציוד מקצועי מתקדם. כולל רכב חברה. הכשרה מלאה ניתנת. הצוות שלנו פרחח ונחמד!",
    requirements: ["כושר פיזי", "רישיון נהיגה", "זמינות מלאה", "נכונות ללמוד"],
    questions: ["האם יש לך ניסיון בניקוי שטיחים?", "האם אתה זמין להתחיל מיד?", "האם יש לך רישיון נהיגה?"],
  },
  {
    id: "m12",
    title: "טכנאי ניקוי שטיחים בכיר",
    company: "Carpet Care Pro",
    salary: "$750-1,100/שבוע",
    location: "New Jersey",
    hours: "9:00-18:00",
    categories: ["carpets"],
    car: true,
    license: false,
    housing: false,
    weekend: false,
    description: "Carpet Care Pro מגייסת טכנאי ניקוי שטיחים בכיר לניו ג'רזי. ניסיון נדרש. כולל רכב וציוד מקצועי. אפשרות לבונוסים על עבודה מצוינת.",
    requirements: ["ניסיון של שנה+", "רישיון נהיגה", "ידע בציוד ניקוי", "שירותיות"],
    questions: ["כמה ניסיון יש לך בניקוי שטיחים?", "האם יש לך ניסיון עם ציוד מקצועי?", "האם אתה מוכן לעבוד בניו ג'רזי?"],
  },
  {
    id: "m13",
    title: "סוכן מכירות שטח",
    company: "Sales Force NY",
    salary: "$1,000-2,500/שבוע",
    location: "Manhattan, NY",
    hours: "9:00-18:00",
    categories: ["sales"],
    car: true,
    license: true,
    housing: false,
    weekend: false,
    description: "Sales Force NY מחפשת סוכן מכירות שטח אגרסיבי ומוכשר. שכר בסיס + עמלות גבוהות. ללא תקרת שכר! הצוות הישראלי שלנו הוא הטוב ביותר בתחום.",
    requirements: ["ניסיון במכירות", "כריזמה ויכולת שכנוע", "רישיון נהיגה", "רישיון עבודה"],
    questions: ["האם יש לך ניסיון במכירות?", "מה הסגירה הגדולה ביותר שלך?", "האם אתה מוכן לעבוד בשכר עמלות?"],
  },
  {
    id: "m14",
    title: "מוכר/ת עגלות ומוצרים",
    company: "Street Vendors Inc",
    salary: "$600-1,000/שבוע",
    location: "Brooklyn, NY",
    hours: "10:00-19:00",
    categories: ["sales"],
    car: false,
    license: false,
    housing: false,
    weekend: true,
    description: "Street Vendors Inc מחפשת מוכרים לעגלות ברחבי ברוקלין. עבודה בחוץ, סביבה דינמית, כיף גדול! אין צורך בניסיון. מתאים גם לסטודנטים.",
    requirements: ["חיוכי ושירותי", "זמינות לסופי שבוע", "יכולת עמידה ממושכת", "אנגלית בסיסית"],
    questions: ["האם אתה זמין לסופי שבוע?", "האם יש לך ניסיון במכירות?", "מה הזמינות השבועית שלך?"],
  },
  {
    id: "m15",
    title: "מנהל מכירות אזורי",
    company: "NY Sales Group",
    salary: "$1,500-3,000/שבוע",
    location: "Queens, NY",
    hours: "9:00-18:00",
    categories: ["sales"],
    car: true,
    license: true,
    housing: false,
    weekend: false,
    description: "NY Sales Group מגייסת מנהל מכירות אזורי מנוסה לקווינס. ניהול צוות מכירות, קביעת יעדים, ובניית קשרי לקוחות. חבילת שכר בין הגבוהות בשוק.",
    requirements: ["ניסיון ניהולי של 3+ שנים", "רקורד מוכח במכירות", "רישיון נהיגה", "רישיון עבודה"],
    questions: ["כמה שנות ניסיון ניהולי יש לך?", "מה הצוות הגדול ביותר שניהלת?", "מה ההישג המכירתי הגדול ביותר שלך?"],
  },
];
